module.exports = {
  USER_REGISTERED: 'USER_REGISTERED',
  TEST_DRIVE_BOOKED: 'TEST_DRIVE_BOOKED',
  TEST_DRIVE_STATUS_CHANGED: 'TEST_DRIVE_STATUS_CHANGED',
  INQUIRY_CREATED: 'INQUIRY_CREATED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  CAR_STATUS_CHANGED: 'CAR_STATUS_CHANGED'
};
